profile-debug: config --profile debug -x _debug --cmake-args -DCMAKE_BUILD_TYPE=Debug
profile-release: config --profile release -x _release --cmake-args -DCMAKE_BUILD_TYPE=Release
extend-sys: config --profile sys --extend /opt/ros/indigo -x _sys
extend-overlay: config --profile overlay --extend ~/ros/indigo/install -x _overlay
