profile-debug: config --profile debug -x _debug --cmake-args -DCMAKE_BUILD_TYPE=Debug
profile-release: config --profile release -x _release --cmake-args -DCMAKE_BUILD_TYPE=Release
profile-reldeb: config --profile reldeb -x _reldeb --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo
profile-uftrace: config --profile uftrace -x _uftrace --cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-fno-inline -pg"
profile-clang: config --profile clang -x _clang --cmake-args -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
profile-clang-debug: config --profile clang-debug -x _clang_debug --cmake-args -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Debug
profile-clang-release: config --profile clang-release -x _clang_release --cmake-args -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release
profile-melodic: config --profile melodic -x _melodic
profile-noetic: config --profile noetic -x _noetic
